"""whatever

Revision ID: 70323b6e931a
Revises: 
Create Date: 2020-06-04 20:20:44.661154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70323b6e931a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('password', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('avenger_num',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('avenger_name', sa.String(length=200), nullable=True),
    sa.Column('phone_num', sa.String(length=10), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('avenger_num')
    op.drop_table('user')
    # ### end Alembic commands ###
